params:
    L: 30
    L_a: 480
    staff_velocity: 0.58
    drone_velocity: 0.83
    num_staff: 2
    cus_per_staff: -1
    distance_coeff: 0.7

data_path: data/d1/12.20.2.txt

result_folder: result

solver:
    solver: SCIP #CBC
    num_worker: -1
    time_limit: 18000000

tech2color: {-1: "blue", 0: "red", 1: "green", 2: "silver", 3: "yellow"}

#use for test
staff_trip: [[0,1,11,13], [0,5,9,8,13],[0,6,10,12,2,4,7,3,13]]
drone_trip: [[1,10], [12], [11], [2], [4]]