params:
    L: 30
    L_a: 480
    staff_velocity: 0.58
    drone_velocity: 0.83
    num_staff: 2
    cus_per_staff: -1
    distance_coeff: -1

data_path: data/d1/6.5.1.txt

result_folder: result

solver:
    solver: CPLEX #CBC, SCIP, GUROBI, CPLEX
    num_worker: -1
    time_limit: 120
    model_params:
        gurobi: {} # tham so dac biet cho gurobi, format name:value
        cplex: {} # tham so dac biet cho cplex, format id:value, xem id model.parameters


tech2color: {-1: "blue", 0: "red", 1: "green", 2: "silver", 3: "yellow", 4: "orange", 5: "violet", 6: "gray"}

#use for test
staff_trip: [[0,3,1,6,4,2,7], [0,5,7]]
drone_trip: [[3],[1],[6],[4],[2]]