params:
    L: 30
    L_a: 180
    staff_velocity: 0.58
    drone_velocity: 0.83
    num_staff: 2
    cus_per_staff: 5

data_path: data/d1/6*.txt

result_folder: result

solver:
    solver: SCIP #CBC
    num_worker: -1
    time_limit: 18000000

tech2color: {-1: "blue", 0: "red", 1: "green", 2: "silver", 3: "yellow"}