params:
    L: 30
    L_a: 480
    staff_velocity: 0.58
    drone_velocity: 0.83
    num_staff: 2
    cus_per_staff: -1
    distance_coeff: -1

data_path: data/d1/6.5.1.txt

result_folder: result

solver:
    solver: GUROBI #CBC SCIP
    num_worker: -1
    time_limit: 180

tech2color: {-1: "blue", 0: "red", 1: "green", 2: "silver", 3: "yellow"}

#use for test
staff_trip: [[0,5,4,8,11], [0,10,9,2,7,3,6,1,11]]
drone_trip: [[10,5], [9,4,8], [2], [3]]