params:
    L: 30
    L_a: 480
    staff_velocity: 0.58
    drone_velocity: 0.83
    num_staff: 2
    cus_per_staff: -1
    distance_coeff: 0.5

data_path: data/d1/6.5.1.txt

result_folder: result

solver:
    solver: GUROBI #CBC SCIP
    num_worker: -1
    time_limit: 120

tech2color: {-1: "blue", 0: "red", 1: "green", 2: "silver", 3: "yellow"}

#use for test
staff_trip: [[0,2,3,5,6,4,1,7]]
drone_trip: [[2], [3], [5], [6], [4], [1]]